spring:
  application:
    name: server

  datasource:
    url: jdbc:mysql://localhost:3306/lost_found?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: #连结池
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
# 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  #单个文件最大10MB
      max-request-size: 10MB

  profiles:
    active: dev

server:
  port: 8080

# JWT
jwt:
  secret: 8fK2#kD9@aL!xP0qZrT7vW3yH6mN1sBZ    #签名密钥
  expiration-ms: 604800000         #过期时间ms

# 微信小程序
wechat:
  appid: wxd59d9e3110ab847e
  secret: 

# 百度图像识别
baidu:
  ai:
    app-id: "7604831"
    api-key: "10zKw7zuDpdK9Q972M8fbVlH"
    secret-key: "HJRnE2A9htymXdKib5dKFLHocNhc0ybr"

# 文件上传路径
upload:
  path: ./uploads   #文件保存位置
  url-prefix: /uploads  #
